---
title: "01a Experiments"
output: html_document
date: "2023-04-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("01z Functions.R")
```

## Board 1

```{r}
board <- list()
board$dim <- 4
board$ladders <- data.frame(ladder.starts = c(3,5),ladder.ends = c(10,12))
board$snakes <- data.frame(snakes.starts = c(11,15), snakes.ends = c(4,8))
board
```

```{r}
play(board,state=16)
```

```{r}
library(glue)
```


```{r}
rolls <- c()
for(j in 1:16){
  rolls <- c()
  for(i in 1:10000){
    rolls <- c(rolls,play(board,state=j))
  }
  m <- round(mean(rolls),2)
  s <- round(sd(rolls)^2,2)
  hist(rolls,breaks=50,xlim=c(0, 50),main=glue("State {j} Start: # of Rolls to Win."))
  mtext(glue(" Mean = {m}. Var = {s}."), side=3, line = - 2)
  abline(v=m, col='red')
}
```



# Board 2

```{r}
set.seed(47)
board <- initialize.board(12,12,12)
```

```{r}
plays2 <- c()
for(i in 1:1000){
  plays2 <- c(plays2,play(board))
}
```

```{r}

hist(plays2,breaks=100)
mean(plays2)
sd(plays2)^2
boxplot(plays2)
```




