---
title: "01b Modeling"
output: html_document
date: "2023-04-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# for converting decimals to fractions
library(MASS)
```

```{r}
source("01z Functions.R")
```

```{r}
trans.mat <- function(board){
  spaces <- (board$dim)^2
  tm <- matrix(0,nrow=spaces,ncol=spaces)
  for(i in 1:(spaces)){
    for(j in 1:6){
      if( (i+j) %in% board$ladders$ladder.starts){
        index <- which(board$ladders$ladder.starts == (i+j))
        tm[i,board$ladders$ladder.ends[index]] <- tm[i,board$ladders$ladder.ends[index]]+1/6
      }
      else if( (i+j) %in% board$snakes$snakes.starts){
        index <- which(board$snakes$snakes.starts == (i+j))
        tm[i,board$snakes$snakes.ends[index]] <- tm[i,board$snakes$snakes.ends[index]] +1/6
      }
      else{
        if(i+j > spaces) tm[i,i] <- tm[i,i]+1/6
        else tm[i,i+j] <- tm[i,i+j]+1/6
      }
    }
  }
  
  tm[spaces,spaces] <- 1
  
  return(fractions(tm))
}
```

## Sanity Check

```{r}
sum(trans.mat(board))
```
```{r}
for(i in 1:board$dim^2) print(sum(trans.mat(board)[i,]))
```

```{r}
print.tm <- function(tm){
  p <- ""
  for(i in 1:nrow(tm)){
    for(j in 1:ncol(tm)){
      if(j==ncol(tm)) p <- paste(p,tm[i,j],'\\\\','\n')
      else p <- paste(p, tm[i,j], '&')
    }
  }
  
  cat(p)
}
```

```{r}
# expected Number of turns and variance until Absorbing state (win)
E.V.turns.vector <- function(board){ 
  tm <- trans.mat(board)
  
  F.dim <- board$dim^2-1
  Q <- tm[1:F.dim,1:F.dim]
  I <- matrix(0,nrow=F.dim,ncol=F.dim); for(i in 1:F.dim) I[i,i] <- 1
  
  N <- solve(I-Q) # F
  one.vec <- matrix(1,nrow=F.dim,ncol=1)
  
  expected <- N%*%one.vec
  t.squared <- expected^2 # element-wise squared
  
  variance <- (2*N-I)%*%expected - t.squared
  
  return(list(expected=round(expected,2),sd=round(sqrt(variance),2),variance=round(variance,2)))
}
```

```{r}
expected.turns <- function(board,start.state){
  tm <- trans.mat(board)
  
  F.dim <- board$dim^2-1
  Q <- tm[1:F.dim,1:F.dim]
  I <- matrix(0,nrow=F.dim,ncol=F.dim); for(i in 1:F.dim) I[i,i] <- 1
  one.vec <- matrix(1,nrow=F.dim,ncol=1)
  
  return(round(solve(I-Q) %*% one.vec,2)[start.state])
}
```

# Board 1

```{r}
board <- list()
board$dim <- 4
board$ladders <- data.frame(ladder.starts = c(3,5),ladder.ends = c(10,12))
board$snakes <- data.frame(snakes.starts = c(11,15), snakes.ends = c(4,8))
```

```{r}
tm <- trans.mat(board)
# print.tm(tm)
sum(tm)
```

```{r}
EV <- E.V.turns.vector(board)
sqrt(EV$variance)
```

# Board 2

```{r}
set.seed(47)
board <- initialize.board(12,12,12)
# board
```

```{r}
EV <- E.V.turns.vector(board)
EV$expected
EV$sd
```



