---
title: "Functions To HTML"
output: html_document
date: "2023-04-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

initialize.board <- function(dim, n.ladders, n.snakes){
  
  spaces <- dim^2
  
  occupied <- c()
  
  ladder.starts <- sample(size=n.ladders,1:(spaces-dim),replace=FALSE)
  occupied <- c(occupied,ladder.starts)
  
  ladder.ends <- c()
  for(i in 1:n.ladders){
    le <- ceiling(ladder.starts[i]/dim)*dim # ensures ladder ends at least one row above
    m <- min(40,spaces-1-le)
    end <- le+sample(size=1,1:m)
    while(end %in% occupied){
      end <- le+sample(size=1,1:m)
    } 
    occupied <- c(occupied, end)
    ladder.ends <- c(ladder.ends,end)
  }
  
  snakes.starts <- c()
  for(i in 1:n.snakes){
    ss <- sample(size=1,(dim+1):(spaces-1),replace=FALSE)
    while(ss %in% occupied){
      ss <- sample(size=1,(dim+1):(spaces-1),replace=FALSE)
    }
    occupied <- c(occupied, ss)
    snakes.starts <- c(snakes.starts,ss)
  }
  
  snakes.ends <- c()
  for(i in 1:n.snakes){
    se <- floor(snakes.starts[i]/dim)*dim # ensures snake ends at least one row below
    m <- min(40,se)
    end <- se-sample(size=1,0:m)
    while(end %in% occupied){
      end <- se-sample(size=1,0:m)
    }
    occupied <- c(occupied, end)
    snakes.ends <- c(snakes.ends,end)
  }
  
  ladders <- data.frame(ladder.starts,ladder.ends)
  snakes <- data.frame(snakes.starts,snakes.ends)
  
  return(list(dim=dim,ladders=ladders,snakes=snakes))
  
}

# Simulation Functions

roll.die <- function(){
  return(sample(size=1,1:6))
}

play.turn <- function(state,board){
  
  ladders <- board$ladders
  snakes <- board$snakes
  
  initial.state <- state
  state <- state + roll.die()
  
  if(state %in% ladders[,1]){
    state <- ladders[which(ladders[,1] == state),2]
  }
  else if(state %in% snakes[,1]){
    state <- snakes[which(snakes[,1] == state),2]
  }
  
  if(state > board$dim^2) return(initial.state)
  
  return(state)
  
}

play <- function(board,state=1){
  turns <- 0
  
  while(state < (board$dim)^2){
    
    state <- play.turn(state,board)
    turns <- turns+1
    
  }
  
  return(turns)
}

# Markov Chains Modeling Functions

trans.mat <- function(board){
  spaces <- (board$dim)^2
  tm <- matrix(0,nrow=spaces,ncol=spaces)
  for(i in 1:(spaces)){
    for(j in 1:6){
      if( (i+j) %in% board$ladders$ladder.starts){
        index <- which(board$ladders$ladder.starts == (i+j))
        tm[i,board$ladders$ladder.ends[index]] <- tm[i,board$ladders$ladder.ends[index]]+1/6
      }
      else if( (i+j) %in% board$snakes$snakes.starts){
        index <- which(board$snakes$snakes.starts == (i+j))
        tm[i,board$snakes$snakes.ends[index]] <- tm[i,board$snakes$snakes.ends[index]] +1/6
      }
      else{
        if(i+j > spaces) tm[i,i] <- tm[i,i]+1/6
        else tm[i,i+j] <- tm[i,i+j]+1/6
      }
    }
  }
  
  tm[spaces,spaces] <- 1
  
  return(fractions(tm))
}

print.tm <- function(tm){
  p <- ""
  for(i in 1:nrow(tm)){
    for(j in 1:ncol(tm)){
      if(j==ncol(tm)) p <- paste(p,tm[i,j],'\\\\','\n')
      else p <- paste(p, tm[i,j], '&')
    }
  }
  
  cat(p)
}

E.V.turns.vector <- function(board){ 
  tm <- trans.mat(board)
  
  F.dim <- board$dim^2-1
  Q <- tm[1:F.dim,1:F.dim]
  I <- matrix(0,nrow=F.dim,ncol=F.dim); for(i in 1:F.dim) I[i,i] <- 1
  
  N <- solve(I-Q) # F
  one.vec <- matrix(1,nrow=F.dim,ncol=1)
  
  expected <- N%*%one.vec
  t.squared <- expected^2 # element-wise squared
  
  variance <- (2*N-I)%*%expected - t.squared
  
  return(list(expected=round(expected,2),variance=round(variance,2)))
}


```
